name: 'BrowserStack'
on: [push, pull_request]

jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest
    steps:
      - name: 'BrowserStack Env Setup'
        uses: 'Baaryan/github-actions/setup-env@v1.0.2'
        with:
          username:  ${{secrets.BROWSERSTACK_USERNAME}}
          access-key: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
          build-name: BUILD_INFO
      - name: 'BrowserStackLocal Setup'
        uses: 'Baaryan/github-actions/setup-local@v1.0.2'
        with:
          local-testing: start
          local-logging-level: all-logs
          local-identifier: random
      - name: 'checkout the repository demo'
        uses: 'actions/checkout@v2'
      - name: 'running npm install'
        run: 'npm install'
      - name: 'running http-server'
        run: './node_modules/.bin/http-server -p 8099 &'
      - name: 'run test'
        run: 'node index.js'
      - name: 'BrowserStackLocal Stop'
        uses: 'Baaryan/github-actions/setup-local@v1.0.2'
        with:
          local-testing: stop
